# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'olveraProject_Kef.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1076, 762)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(990, 745))
        MainWindow.setMaximumSize(QtCore.QSize(5000, 5000))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("razor.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.MyForm = QtGui.QWidget(MainWindow)
        self.MyForm.setStyleSheet(_fromUtf8("#MyForm {\n"
"background: gray;\n"
"}\n"
"\n"
"#FrameMenu {\n"
"border: 3px solid gray;\n"
"background: white;\n"
"border-radius: 10px;\n"
"\n"
"}\n"
""))
        self.MyForm.setObjectName(_fromUtf8("MyForm"))
        self.Titulo = QtGui.QLabel(self.MyForm)
        self.Titulo.setGeometry(QtCore.QRect(140, 10, 451, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Titulo.setFont(font)
        self.Titulo.setStyleSheet(_fromUtf8("color: white;"))
        self.Titulo.setTextFormat(QtCore.Qt.RichText)
        self.Titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.Titulo.setObjectName(_fromUtf8("Titulo"))
        self.QUOTE = QtGui.QLabel(self.MyForm)
        self.QUOTE.setGeometry(QtCore.QRect(40, 660, 871, 51))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QUOTE.sizePolicy().hasHeightForWidth())
        self.QUOTE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poiret One"))
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.QUOTE.setFont(font)
        self.QUOTE.setStyleSheet(_fromUtf8("color: white;"))
        self.QUOTE.setTextFormat(QtCore.Qt.PlainText)
        self.QUOTE.setScaledContents(False)
        self.QUOTE.setAlignment(QtCore.Qt.AlignCenter)
        self.QUOTE.setWordWrap(True)
        self.QUOTE.setObjectName(_fromUtf8("QUOTE"))
        self.Aclaracion = QtGui.QLabel(self.MyForm)
        self.Aclaracion.setGeometry(QtCore.QRect(650, 10, 261, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Aclaracion.sizePolicy().hasHeightForWidth())
        self.Aclaracion.setSizePolicy(sizePolicy)
        self.Aclaracion.setStyleSheet(_fromUtf8("color: white;"))
        self.Aclaracion.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.Aclaracion.setWordWrap(True)
        self.Aclaracion.setObjectName(_fromUtf8("Aclaracion"))
        self.tabWidget2 = QtGui.QTabWidget(self.MyForm)
        self.tabWidget2.setEnabled(True)
        self.tabWidget2.setGeometry(QtCore.QRect(20, 40, 971, 631))
        self.tabWidget2.setObjectName(_fromUtf8("tabWidget2"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.MenuFrame = QtGui.QFrame(self.tab)
        self.MenuFrame.setGeometry(QtCore.QRect(10, 10, 931, 591))
        self.MenuFrame.setStyleSheet(_fromUtf8("\n"
"#MenuFrame {\n"
"border: 3px solid gray;\n"
"background: white;\n"
"border-radius: 10px;\n"
"\n"
"}"))
        self.MenuFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.MenuFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.MenuFrame.setObjectName(_fromUtf8("MenuFrame"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.MenuFrame)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 20, 911, 571))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.menuLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.menuLayout.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.menuLayout.setMargin(5)
        self.menuLayout.setObjectName(_fromUtf8("menuLayout"))
        self._1_hLay = QtGui.QHBoxLayout()
        self._1_hLay.setObjectName(_fromUtf8("_1_hLay"))
        self._1step = QtGui.QFrame(self.verticalLayoutWidget_3)
        self._1step.setFrameShape(QtGui.QFrame.StyledPanel)
        self._1step.setFrameShadow(QtGui.QFrame.Raised)
        self._1step.setObjectName(_fromUtf8("_1step"))
        self.layoutWidget = QtGui.QWidget(self._1step)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 891, 79))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self._1dataLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self._1dataLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self._1dataLayout.setMargin(5)
        self._1dataLayout.setSpacing(5)
        self._1dataLayout.setObjectName(_fromUtf8("_1dataLayout"))
        self.label_step1 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto"))
        font.setPointSize(12)
        self.label_step1.setFont(font)
        self.label_step1.setObjectName(_fromUtf8("label_step1"))
        self._1dataLayout.addWidget(self.label_step1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.fileTraining_btn = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileTraining_btn.sizePolicy().hasHeightForWidth())
        self.fileTraining_btn.setSizePolicy(sizePolicy)
        self.fileTraining_btn.setObjectName(_fromUtf8("fileTraining_btn"))
        self.verticalLayout_2.addWidget(self.fileTraining_btn)
        self.fileOpen_lbl = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileOpen_lbl.sizePolicy().hasHeightForWidth())
        self.fileOpen_lbl.setSizePolicy(sizePolicy)
        self.fileOpen_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.fileOpen_lbl.setObjectName(_fromUtf8("fileOpen_lbl"))
        self.verticalLayout_2.addWidget(self.fileOpen_lbl)
        self._1dataLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.fileTest_btn = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileTest_btn.sizePolicy().hasHeightForWidth())
        self.fileTest_btn.setSizePolicy(sizePolicy)
        self.fileTest_btn.setObjectName(_fromUtf8("fileTest_btn"))
        self.verticalLayout_3.addWidget(self.fileTest_btn)
        self.fileOpen_lbl_2 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileOpen_lbl_2.sizePolicy().hasHeightForWidth())
        self.fileOpen_lbl_2.setSizePolicy(sizePolicy)
        self.fileOpen_lbl_2.setAlignment(QtCore.Qt.AlignCenter)
        self.fileOpen_lbl_2.setObjectName(_fromUtf8("fileOpen_lbl_2"))
        self.verticalLayout_3.addWidget(self.fileOpen_lbl_2)
        self._1dataLayout.addLayout(self.verticalLayout_3)
        self.label = QtGui.QLabel(self._1step)
        self.label.setGeometry(QtCore.QRect(170, -60, 559, 78))
        self.label.setObjectName(_fromUtf8("label"))
        self._1_hLay.addWidget(self._1step)
        self.menuLayout.addLayout(self._1_hLay)
        self.line = QtGui.QFrame(self.verticalLayoutWidget_3)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.menuLayout.addWidget(self.line)
        self._2_hLay = QtGui.QHBoxLayout()
        self._2_hLay.setObjectName(_fromUtf8("_2_hLay"))
        self._2step = QtGui.QFrame(self.verticalLayoutWidget_3)
        self._2step.setEnabled(True)
        self._2step.setFrameShape(QtGui.QFrame.StyledPanel)
        self._2step.setFrameShadow(QtGui.QFrame.Raised)
        self._2step.setObjectName(_fromUtf8("_2step"))
        self.label_step2 = QtGui.QLabel(self._2step)
        self.label_step2.setGeometry(QtCore.QRect(10, 10, 121, 81))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_step2.sizePolicy().hasHeightForWidth())
        self.label_step2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto"))
        font.setPointSize(12)
        self.label_step2.setFont(font)
        self.label_step2.setWordWrap(True)
        self.label_step2.setObjectName(_fromUtf8("label_step2"))
        self.groupBox = QtGui.QGroupBox(self._2step)
        self.groupBox.setGeometry(QtCore.QRect(160, 0, 471, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 451, 68))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.radio_knn = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radio_knn.setChecked(True)
        self.radio_knn.setObjectName(_fromUtf8("radio_knn"))
        self.gridLayout.addWidget(self.radio_knn, 0, 0, 1, 1)
        self.radio_ctree = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radio_ctree.setObjectName(_fromUtf8("radio_ctree"))
        self.gridLayout.addWidget(self.radio_ctree, 1, 0, 1, 1)
        self.radio_random = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radio_random.setObjectName(_fromUtf8("radio_random"))
        self.gridLayout.addWidget(self.radio_random, 1, 1, 1, 1)
        self.radio_logistic = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radio_logistic.setObjectName(_fromUtf8("radio_logistic"))
        self.gridLayout.addWidget(self.radio_logistic, 0, 1, 1, 1)
        self.radio_svm = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radio_svm.setObjectName(_fromUtf8("radio_svm"))
        self.gridLayout.addWidget(self.radio_svm, 0, 2, 1, 1)
        self.radio_net = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radio_net.setObjectName(_fromUtf8("radio_net"))
        self.gridLayout.addWidget(self.radio_net, 1, 2, 1, 1)
        self.label_classifier = QtGui.QLabel(self._2step)
        self.label_classifier.setGeometry(QtCore.QRect(740, 10, 141, 81))
        self.label_classifier.setWordWrap(True)
        self.label_classifier.setObjectName(_fromUtf8("label_classifier"))
        self.chooseClass_btn = QtGui.QToolButton(self._2step)
        self.chooseClass_btn.setGeometry(QtCore.QRect(640, 30, 81, 41))
        self.chooseClass_btn.setObjectName(_fromUtf8("chooseClass_btn"))
        self._2_hLay.addWidget(self._2step)
        self.menuLayout.addLayout(self._2_hLay)
        self.line_2 = QtGui.QFrame(self.verticalLayoutWidget_3)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.menuLayout.addWidget(self.line_2)
        self._3_hLay = QtGui.QHBoxLayout()
        self._3_hLay.setObjectName(_fromUtf8("_3_hLay"))
        self._3step = QtGui.QFrame(self.verticalLayoutWidget_3)
        self._3step.setEnabled(True)
        self._3step.setFrameShape(QtGui.QFrame.StyledPanel)
        self._3step.setFrameShadow(QtGui.QFrame.Raised)
        self._3step.setObjectName(_fromUtf8("_3step"))
        self.tabWidget = QtGui.QTabWidget(self._3step)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(170, 0, 721, 91))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_knn = QtGui.QWidget()
        self.tab_knn.setObjectName(_fromUtf8("tab_knn"))
        self.label_2 = QtGui.QLabel(self.tab_knn)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.spinBox__KNN_numVecinos = QtGui.QSpinBox(self.tab_knn)
        self.spinBox__KNN_numVecinos.setGeometry(QtCore.QRect(120, 10, 51, 20))
        self.spinBox__KNN_numVecinos.setMinimum(1)
        self.spinBox__KNN_numVecinos.setProperty("value", 3)
        self.spinBox__KNN_numVecinos.setObjectName(_fromUtf8("spinBox__KNN_numVecinos"))
        self.comboBox_KNN_metrica = QtGui.QComboBox(self.tab_knn)
        self.comboBox_KNN_metrica.setGeometry(QtCore.QRect(230, 10, 111, 20))
        self.comboBox_KNN_metrica.setObjectName(_fromUtf8("comboBox_KNN_metrica"))
        self.comboBox_KNN_metrica.addItem(_fromUtf8(""))
        self.comboBox_KNN_metrica.addItem(_fromUtf8(""))
        self.comboBox_KNN_metrica.addItem(_fromUtf8(""))
        self.comboBox_KNN_metrica.addItem(_fromUtf8(""))
        self.label_3 = QtGui.QLabel(self.tab_knn)
        self.label_3.setGeometry(QtCore.QRect(360, 0, 71, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.tab_knn)
        self.label_4.setGeometry(QtCore.QRect(190, 0, 61, 34))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.comboBox_KNN_peso = QtGui.QComboBox(self.tab_knn)
        self.comboBox_KNN_peso.setGeometry(QtCore.QRect(410, 10, 111, 20))
        self.comboBox_KNN_peso.setObjectName(_fromUtf8("comboBox_KNN_peso"))
        self.comboBox_KNN_peso.addItem(_fromUtf8(""))
        self.comboBox_KNN_peso.addItem(_fromUtf8(""))
        self.label_5 = QtGui.QLabel(self.tab_knn)
        self.label_5.setGeometry(QtCore.QRect(530, 0, 71, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.comboBox_KNN_algo = QtGui.QComboBox(self.tab_knn)
        self.comboBox_KNN_algo.setGeometry(QtCore.QRect(590, 10, 111, 20))
        self.comboBox_KNN_algo.setObjectName(_fromUtf8("comboBox_KNN_algo"))
        self.comboBox_KNN_algo.addItem(_fromUtf8(""))
        self.comboBox_KNN_algo.addItem(_fromUtf8(""))
        self.comboBox_KNN_algo.addItem(_fromUtf8(""))
        self.comboBox_KNN_algo.addItem(_fromUtf8(""))
        self.tabWidget.addTab(self.tab_knn, _fromUtf8(""))
        self.tab_tree = QtGui.QWidget()
        self.tab_tree.setEnabled(False)
        self.tab_tree.setObjectName(_fromUtf8("tab_tree"))
        self.tabWidget.addTab(self.tab_tree, _fromUtf8(""))
        self.tab_logis = QtGui.QWidget()
        self.tab_logis.setEnabled(False)
        self.tab_logis.setObjectName(_fromUtf8("tab_logis"))
        self.tabWidget.addTab(self.tab_logis, _fromUtf8(""))
        self.tab_rand = QtGui.QWidget()
        self.tab_rand.setEnabled(False)
        self.tab_rand.setObjectName(_fromUtf8("tab_rand"))
        self.tabWidget.addTab(self.tab_rand, _fromUtf8(""))
        self.tab_svm = QtGui.QWidget()
        self.tab_svm.setEnabled(False)
        self.tab_svm.setObjectName(_fromUtf8("tab_svm"))
        self.tabWidget.addTab(self.tab_svm, _fromUtf8(""))
        self.tav_net = QtGui.QWidget()
        self.tav_net.setEnabled(False)
        self.tav_net.setObjectName(_fromUtf8("tav_net"))
        self.tabWidget.addTab(self.tav_net, _fromUtf8(""))
        self.label_step2_2 = QtGui.QLabel(self._3step)
        self.label_step2_2.setGeometry(QtCore.QRect(10, 10, 151, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_step2_2.sizePolicy().hasHeightForWidth())
        self.label_step2_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto"))
        font.setPointSize(12)
        self.label_step2_2.setFont(font)
        self.label_step2_2.setWordWrap(True)
        self.label_step2_2.setObjectName(_fromUtf8("label_step2_2"))
        self.btn_setParam = QtGui.QToolButton(self._3step)
        self.btn_setParam.setGeometry(QtCore.QRect(20, 50, 91, 31))
        self.btn_setParam.setObjectName(_fromUtf8("btn_setParam"))
        self.label_PARAM = QtGui.QLabel(self._3step)
        self.label_PARAM.setGeometry(QtCore.QRect(120, 60, 41, 21))
        self.label_PARAM.setObjectName(_fromUtf8("label_PARAM"))
        self._3_hLay.addWidget(self._3step)
        self.menuLayout.addLayout(self._3_hLay)
        self.line_3 = QtGui.QFrame(self.verticalLayoutWidget_3)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.menuLayout.addWidget(self.line_3)
        self._4_hLay = QtGui.QHBoxLayout()
        self._4_hLay.setObjectName(_fromUtf8("_4_hLay"))
        self._4step = QtGui.QFrame(self.verticalLayoutWidget_3)
        self._4step.setEnabled(True)
        self._4step.setFrameShape(QtGui.QFrame.StyledPanel)
        self._4step.setFrameShadow(QtGui.QFrame.Raised)
        self._4step.setObjectName(_fromUtf8("_4step"))
        self.btn_test = QtGui.QPushButton(self._4step)
        self.btn_test.setGeometry(QtCore.QRect(460, 30, 121, 31))
        self.btn_test.setObjectName(_fromUtf8("btn_test"))
        self.label_step4 = QtGui.QLabel(self._4step)
        self.label_step4.setGeometry(QtCore.QRect(10, 10, 141, 83))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto"))
        font.setPointSize(12)
        self.label_step4.setFont(font)
        self.label_step4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_step4.setWordWrap(True)
        self.label_step4.setObjectName(_fromUtf8("label_step4"))
        self.btn_train = QtGui.QToolButton(self._4step)
        self.btn_train.setGeometry(QtCore.QRect(250, 10, 91, 71))
        self.btn_train.setObjectName(_fromUtf8("btn_train"))
        self.label_6 = QtGui.QLabel(self._4step)
        self.label_6.setGeometry(QtCore.QRect(720, 60, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.spin_folds = QtGui.QSpinBox(self._4step)
        self.spin_folds.setGeometry(QtCore.QRect(810, 50, 51, 20))
        self.spin_folds.setMinimum(1)
        self.spin_folds.setMaximum(20)
        self.spin_folds.setProperty("value", 5)
        self.spin_folds.setObjectName(_fromUtf8("spin_folds"))
        self.check_strati = QtGui.QCheckBox(self._4step)
        self.check_strati.setGeometry(QtCore.QRect(810, 20, 70, 17))
        self.check_strati.setChecked(True)
        self.check_strati.setObjectName(_fromUtf8("check_strati"))
        self.label_8 = QtGui.QLabel(self._4step)
        self.label_8.setGeometry(QtCore.QRect(370, 40, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.line_5 = QtGui.QFrame(self._4step)
        self.line_5.setGeometry(QtCore.QRect(650, 10, 41, 61))
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_6 = QtGui.QFrame(self._4step)
        self.line_6.setGeometry(QtCore.QRect(710, 10, 3, 61))
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.label_12 = QtGui.QLabel(self._4step)
        self.label_12.setGeometry(QtCore.QRect(730, 0, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.btn_cross = QtGui.QPushButton(self._4step)
        self.btn_cross.setGeometry(QtCore.QRect(720, 30, 81, 31))
        self.btn_cross.setObjectName(_fromUtf8("btn_cross"))
        self._4_hLay.addWidget(self._4step)
        self.menuLayout.addLayout(self._4_hLay)
        self.line_4 = QtGui.QFrame(self.verticalLayoutWidget_3)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.menuLayout.addWidget(self.line_4)
        self._5_hLay = QtGui.QHBoxLayout()
        self._5_hLay.setObjectName(_fromUtf8("_5_hLay"))
        self._5step = QtGui.QFrame(self.verticalLayoutWidget_3)
        self._5step.setEnabled(True)
        self._5step.setFrameShape(QtGui.QFrame.StyledPanel)
        self._5step.setFrameShadow(QtGui.QFrame.Raised)
        self._5step.setObjectName(_fromUtf8("_5step"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self._5step)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(140, 10, 671, 81))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_CA = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_CA.setObjectName(_fromUtf8("label_CA"))
        self.gridLayout_2.addWidget(self.label_CA, 1, 0, 1, 1)
        self.label_F1 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_F1.setObjectName(_fromUtf8("label_F1"))
        self.gridLayout_2.addWidget(self.label_F1, 2, 0, 1, 1)
        self.label_AUC = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_AUC.setObjectName(_fromUtf8("label_AUC"))
        self.gridLayout_2.addWidget(self.label_AUC, 0, 0, 1, 1)
        self.label_RECALL = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_RECALL.setObjectName(_fromUtf8("label_RECALL"))
        self.gridLayout_2.addWidget(self.label_RECALL, 1, 1, 1, 1)
        self.label_PRECISION = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_PRECISION.setObjectName(_fromUtf8("label_PRECISION"))
        self.gridLayout_2.addWidget(self.label_PRECISION, 0, 1, 1, 1)
        self.label_step5 = QtGui.QLabel(self._5step)
        self.label_step5.setGeometry(QtCore.QRect(10, 0, 111, 78))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_step5.sizePolicy().hasHeightForWidth())
        self.label_step5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto"))
        font.setPointSize(12)
        self.label_step5.setFont(font)
        self.label_step5.setWordWrap(True)
        self.label_step5.setObjectName(_fromUtf8("label_step5"))
        self._5_hLay.addWidget(self._5step)
        self.menuLayout.addLayout(self._5_hLay)
        self.verticalLayoutWidget_3.raise_()
        self.tabWidget2.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setEnabled(True)
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.matplotW = MatplotlibWidget(self.tab_2)
        self.matplotW.setGeometry(QtCore.QRect(520, 40, 381, 331))
        self.matplotW.setObjectName(_fromUtf8("matplotW"))
        self.widget = QtGui.QWidget(self.tab_2)
        self.widget.setGeometry(QtCore.QRect(570, 400, 241, 151))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.tableWidget = QtGui.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(40, 40, 371, 291))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(350, 10, 221, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setEnabled(True)
        self.label_9.setGeometry(QtCore.QRect(100, 20, 151, 16))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.btn_matrix = QtGui.QPushButton(self.tab_2)
        self.btn_matrix.setEnabled(True)
        self.btn_matrix.setGeometry(QtCore.QRect(130, 350, 75, 23))
        self.btn_matrix.setObjectName(_fromUtf8("btn_matrix"))
        self.btn_scatter = QtGui.QPushButton(self.tab_2)
        self.btn_scatter.setGeometry(QtCore.QRect(280, 350, 81, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_scatter.sizePolicy().hasHeightForWidth())
        self.btn_scatter.setSizePolicy(sizePolicy)
        self.btn_scatter.setObjectName(_fromUtf8("btn_scatter"))
        self.tabWidget2.addTab(self.tab_2, _fromUtf8(""))
        self.tabWidget2.raise_()
        self.Titulo.raise_()
        self.QUOTE.raise_()
        self.Aclaracion.raise_()
        MainWindow.setCentralWidget(self.MyForm)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1076, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget2.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "DataClassificationKEF", None))
        self.Titulo.setText(_translate("MainWindow", "Data Classification by Kevin Gordillo", None))
        self.QUOTE.setText(_translate("MainWindow", "\"All the things being equal, the simplest solution tends to be the best\" - William of Ockham", None))
        self.Aclaracion.setText(_translate("MainWindow", "This program was made in english beacuse of the need of present information and practice my academic english - Kevin Gordillo", None))
        self.label_step1.setText(_translate("MainWindow", "1. Choose your training set and test set:", None))
        self.fileTraining_btn.setText(_translate("MainWindow", "Open Training Set", None))
        self.fileOpen_lbl.setText(_translate("MainWindow", "Waiting file...", None))
        self.fileTest_btn.setText(_translate("MainWindow", "Open Test Set", None))
        self.fileOpen_lbl_2.setText(_translate("MainWindow", "Waiting file...", None))
        self.label.setText(_translate("MainWindow", "TextLabel", None))
        self.label_step2.setText(_translate("MainWindow", "2. Choose your Classifier", None))
        self.groupBox.setTitle(_translate("MainWindow", "Classifiers", None))
        self.radio_knn.setText(_translate("MainWindow", "KNN", None))
        self.radio_ctree.setText(_translate("MainWindow", "Classification Tree", None))
        self.radio_random.setText(_translate("MainWindow", "Random Forest", None))
        self.radio_logistic.setText(_translate("MainWindow", "Logistic Regression", None))
        self.radio_svm.setText(_translate("MainWindow", "Support Vector Machines", None))
        self.radio_net.setText(_translate("MainWindow", "Neural Network", None))
        self.label_classifier.setText(_translate("MainWindow", "Waiting Classifier", None))
        self.chooseClass_btn.setText(_translate("MainWindow", "Choose\n"
" Classifier", None))
        self.label_2.setText(_translate("MainWindow", "Number of neighbors:", None))
        self.comboBox_KNN_metrica.setItemText(0, _translate("MainWindow", "euclidean", None))
        self.comboBox_KNN_metrica.setItemText(1, _translate("MainWindow", "manhattan", None))
        self.comboBox_KNN_metrica.setItemText(2, _translate("MainWindow", "maximal", None))
        self.comboBox_KNN_metrica.setItemText(3, _translate("MainWindow", "mahalanobis", None))
        self.label_3.setText(_translate("MainWindow", "Weights", None))
        self.label_4.setText(_translate("MainWindow", "Metric", None))
        self.comboBox_KNN_peso.setItemText(0, _translate("MainWindow", "uniform", None))
        self.comboBox_KNN_peso.setItemText(1, _translate("MainWindow", "distance", None))
        self.label_5.setText(_translate("MainWindow", "Algorithm", None))
        self.comboBox_KNN_algo.setItemText(0, _translate("MainWindow", "auto", None))
        self.comboBox_KNN_algo.setItemText(1, _translate("MainWindow", "ball_tree", None))
        self.comboBox_KNN_algo.setItemText(2, _translate("MainWindow", "kd_tree", None))
        self.comboBox_KNN_algo.setItemText(3, _translate("MainWindow", "brute", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_knn), _translate("MainWindow", "KNN", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tree), _translate("MainWindow", "Classification Tree", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_logis), _translate("MainWindow", "Logistic Regression", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_rand), _translate("MainWindow", "Random Forest", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_svm), _translate("MainWindow", "SVM", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tav_net), _translate("MainWindow", "Neural Network", None))
        self.label_step2_2.setText(_translate("MainWindow", "3. Edit Parameters", None))
        self.btn_setParam.setText(_translate("MainWindow", "Set \n"
" Parameters", None))
        self.label_PARAM.setText(_translate("MainWindow", "OK", None))
        self.btn_test.setText(_translate("MainWindow", "Test Learner", None))
        self.label_step4.setText(_translate("MainWindow", "4. Process your data and sampling", None))
        self.btn_train.setText(_translate("MainWindow", "Train learner\n"
" using trainer set", None))
        self.label_6.setText(_translate("MainWindow", "Number of folds:", None))
        self.check_strati.setText(_translate("MainWindow", "Stratified", None))
        self.label_8.setText(_translate("MainWindow", "Using Test Set", None))
        self.label_12.setText(_translate("MainWindow", "CrossValidation Parameters", None))
        self.btn_cross.setText(_translate("MainWindow", "Cross Validation", None))
        self.label_CA.setText(_translate("MainWindow", "CA", None))
        self.label_F1.setText(_translate("MainWindow", "F1", None))
        self.label_AUC.setText(_translate("MainWindow", "AUC", None))
        self.label_RECALL.setText(_translate("MainWindow", "RECALL", None))
        self.label_PRECISION.setText(_translate("MainWindow", "PRECISION", None))
        self.label_step5.setText(_translate("MainWindow", "5. Projections adn results", None))
        self.tabWidget2.setTabText(self.tabWidget2.indexOf(self.tab), _translate("MainWindow", "Process", None))
        self.label_7.setText(_translate("MainWindow", "Graphics Area", None))
        self.label_9.setText(_translate("MainWindow", "Confusion Matrix", None))
        self.btn_matrix.setText(_translate("MainWindow", "Matrix", None))
        self.btn_scatter.setText(_translate("MainWindow", "Confusion Plot", None))
        self.tabWidget2.setTabText(self.tabWidget2.indexOf(self.tab_2), _translate("MainWindow", "Table", None))

from matplotlibwidget import MatplotlibWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

